### Sample POST request to create a new entry in the staging container
POST http://localhost:7071/api/devtoberfest/staging/marvel/
Content-Type: application/json

{
  "id": "{{$guid}}",
  "nickName": "Hulk",
  "email":"bruce.banner@avengers.com",
  "location": {
      "region": "massachusetts",
      "country": "usa"
  }
}      
